### ISSUE TITLE
[trace_gen] Cannot generate traces from the dot file

### ISSUE THREAD

**Issue by thanhtoantnt** [scuptio/sedeve-kit#22]
Firstly, I found your ideas interesting since we are also working on how to use the TLA+ specifications to test the implementation. Hence, I hope that your tool `trace_gen` can help me to generate traces that be translated into actions in unit tests.

However, it seems that I always got 0 trace when using `trace_gen`.
I used this simple dot file `threads.dot` generated using `tlc -dump` command.
```
strict digraph DiskGraph {
nodesep=0.35;
subgraph cluster_graph {
color="white";
2871532761935906954 [label="/\\ lock = 0\n/\\ pc = <<\"GetLock\", \"GetLock\">>",style = filled]
2871532761935906954 -> -212251656185234960 [label="",color="black",fontcolor="black"];
-212251656185234960 [label="/\\ lock = 1\n/\\ pc = <<\"ReleaseLock\", \"GetLock\">>"];
2871532761935906954 -> -4694398903703039799 [label="",color="black",fontcolor="black"];
-4694398903703039799 [label="/\\ lock = 2\n/\\ pc = <<\"GetLock\", \"ReleaseLock\">>"];
-212251656185234960 -> -3372465716983143921 [label="",color="black",fontcolor="black"];
-3372465716983143921 [label="/\\ lock = 0\n/\\ pc = <<\"Reset\", \"GetLock\">>"];
-4694398903703039799 -> -4052949302994118316 [label="",color="black",fontcolor="black"];
-4052949302994118316 [label="/\\ lock = 0\n/\\ pc = <<\"GetLock\", \"Reset\">>"];
-3372465716983143921 -> 2871532761935906954 [label="",color="black",fontcolor="black"];
-3372465716983143921 -> -488802265503438507 [label="",color="black",fontcolor="black"];
-488802265503438507 [label="/\\ lock = 2\n/\\ pc = <<\"Reset\", \"ReleaseLock\">>"];
-4052949302994118316 -> 5244035372738178278 [label="",color="black",fontcolor="black"];
5244035372738178278 [label="/\\ lock = 1\n/\\ pc = <<\"ReleaseLock\", \"Reset\">>"];
-4052949302994118316 -> 2871532761935906954 [label="",color="black",fontcolor="black"];
-488802265503438507 -> -4694398903703039799 [label="",color="black",fontcolor="black"];
-488802265503438507 -> -8458942477330140703 [label="",color="black",fontcolor="black"];
-8458942477330140703 [label="/\\ lock = 0\n/\\ pc = <<\"Reset\", \"Reset\">>"];
5244035372738178278 -> -8458942477330140703 [label="",color="black",fontcolor="black"];
5244035372738178278 -> -212251656185234960 [label="",color="black",fontcolor="black"];
-8458942477330140703 -> -4052949302994118316 [label="",color="black",fontcolor="black"];
-8458942477330140703 -> -3372465716983143921 [label="",color="black",fontcolor="black"];
{rank = same; 2871532761935906954;}
{rank = same; -212251656185234960;-4694398903703039799;}
{rank = same; -3372465716983143921;-4052949302994118316;}
{rank = same; 5244035372738178278;-488802265503438507;}
{rank = same; -8458942477330140703;}
}
}
```

Here is the results of running `trace_gen`:
```
./target/debug/trace_gen -d dot_data/threads.dot -o dot_data/threads.db
2024-04-23T07:35:28.883597Z  INFO src/trace/gen_case.rs:45: use const mapping: {}
2024-04-23T07:35:28.883673Z  INFO src/trace/gen_case.rs:49: Read dot file dot_data/threads.dot
2024-04-23T07:35:28.888684Z  INFO src/trace/gen_case.rs:54: Time elapsed to parse dot_data/threads.dot, time costs: 4.997672ms
2024-04-23T07:35:28.889442Z  INFO src/trace/gen_case.rs:59: Time elapsed to generate action trace, time costs: 694.445µs
2024-04-23T07:35:28.889487Z  INFO src/trace/trace_builder.rs:64: To write traces to DB
2024-04-23T07:35:28.890769Z  INFO src/trace/trace_builder.rs:89: write 0 traces
2024-04-23T07:35:28.890906Z  INFO src/trace/gen_case.rs:81: Time elapsed to gen final trace, time costs: 1.417668ms
```

**Comment by ybbh** [comment]
Sorry for the late reply. 

Currently, we only support reading from the fixed dot output format. The format of a .dot example can be found at: [.dot](https://github.com/scuptio/sedeve-kit/blob//5b68305243285865158d87a40c2a040e165a7f87/src/data/toolbox_dump.dot).
 
The TLA+ toolbox dumps and keeps the interested state to a \_\_action\_\_ variable, and the __trace_gen__ tool only reads the fixed format of the \_\_action\_\_ variable. 

The action must  have a format like:
```
 __action__' =  [
            p |-> Previous State ID,
            i |-> Current State ID,
            s |-> A State Sequence,
            a |-> A Action Sequence
        ]
```
The action keeps the previous and current state IDs for building a graph. You could use [SetAction](https://github.com/scuptio/example-2pc/blob/d88e9c770178fb2afd098532585e9f89356786b1/tlaplus/spec/action.tla#L209) to format the expected format.

We encourage you to use the [SaveValue override operator](https://github.com/scuptio/TLAPlusCommunityModules/blob/91bddeacc415b81220b2a9f65f4d78023514954e/modules/StateDB.tla#L10) to save the interested states into the SQLite database and read from SQLite database using __trace_gen__'s  ["-s, --state-db-path <STATE_DB_PATH>"](https://github.com/scuptio/sedeve-kit/blob/ebbdf4de7df4909ab46592577124ae84da26c98c/src/trace_gen/main.rs#L25) parameter, rather than parse the dumped .dot file. For outputting SQLite database would be more scalable, and parsing a large .dot file would be inefficient (based on personal experience).

The current document still needs improvement and polish; we will add more detailed content later. Welcome to ask here if you have any.

**Comment by ybbh** [comment]
Dumping sqlite db instead.
